
# This is a basic workflow to help you get started with Actions

name: Code coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@master
            - name: Install modules
              run: yarn install
            - name: Run tests
              run: npm run test -- --coverage --watchAll=false
            - name: Upload coverage to codecov
              uses: codecov/codecov-action@v2
