export const SDK_SETTINGS_SET_ENV_ID = 'SDK_SETTINGS/SET_ENV_ID';
export const SDK_SETTINGS_SET_VISITOR_ID = 'SDK_SETTINGS/SET_VISITOR_ID';
export const SDK_SETTINGS_SET_VISITOR_CONTEXT =
  'SDK_SETTINGS/SET_VISITOR_CONTEXT';
export const SDK_SETTINGS_SET_FS_MODIFICATIONS =
  'SDK_SETTINGS_SET_FS_MODIFICATIONS';
