export const SDK_SETTINGS_SET_ENV_ID = 'SDK_SETTINGS/SET_ENV_ID';
export const SDK_SETTINGS_SET_VISITOR_ID = 'SDK_SETTINGS/SET_VISITOR_ID';
export const SDK_SETTINGS_SET_VISITOR_CONTEXT =
  'SDK_SETTINGS/SET_VISITOR_CONTEXT';
export const SDK_SETTINGS_SET_FS_MODIFICATIONS =
  'SDK_SETTINGS_SET_FS_MODIFICATIONS';
export const DEMO_SET_USE_MODIFICATIONS_PARAMS =
  'DEMO_SET_USE_MODIFICATIONS_PARAMS';
export const DEMO_SET_CURRENT_HIT_SELECTED = 'DEMO_SET_CURRENT_HIT_SELECTED';
export const DEMO_UPDATE_HIT_PAYLOAD = 'DEMO_UPDATE_HIT_PAYLOAD';
export const DEMO_RESET = 'DEMO_RESET';
export const DEMO_TOGGLE_SAFE_MODE = 'DEMO_TOGGLE_SAFE_MODE';
export const SDK_SETTINGS_RESET = 'SDK_SETTINGS_RESET';
export const SDK_SETTINGS_UPDATE_CONFIG = 'SDK_SETTINGS_UPDATE_CONFIG';
